title: Yusnia Novita # your name (or website title) here
logo: "/images/fotoyusnia.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A third-year student in the 6th semester of mathematics. I have interested in business development and data analytics
  <br><br>
  I am a career enthusiast with experience in project management, academic activities, and public relations 
  <br><br>
  <a href="https://www.linkedin.com/in/yusnianovita/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
